[package]
name = "stream-processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.5.3"
fake = { version = "2.9.1", features = ["derive"] }
rand = "0.8.5"
rtrb = "0.2.3"
